### ISSUE TITLE
DBans on bancheck

### ISSUE THREAD

**Issue by unseenmagik** [coltoutram/Colts-Cogs#2]
Hi, I am getting this error on installation of bancheck on v3

` from .bancheck import BanList
  File "/home/unseenmagik/.local/share/Red-DiscordBot/MagikBotV3/cogs/CogManager/cogs/bancheck/bancheck.py", l
ine 8, in <module>
    from dbans import DBans
ModuleNotFoundError: No module named 'dbans'`

**Comment by coltoutram** [comment]
I forgot to put that in readme, you need to install
https://github.com/UltimatePancake/dbanspy/tree/async from source or using pip install git+

**Comment by unseenmagik** [comment]
Hi. 
I am unable to install via pip and when cloning the repo above then running it fails. 
do you have a configure guide ?
Thanks

**Comment by coltoutram** [comment]
You can also `git clone https://github.com/UltimatePancake/dbanspy -b async` and then cd into the folder and `pip install .`

**Comment by unseenmagik** [comment]
The response to that is
`ERROR: You must give at least one requirement to install (see "pip help install")`

**Comment by coltoutram** [comment]
Not sure if you're using linux or windows but if you're using linux:
Are you sure you did exactly this
1) `git clone https://github.com/UltimatePancake/dbanspy -b async`
2) `cd dbanspy`
3) `pip install .`

**Comment by unseenmagik** [comment]
On linux. 

Done just that, removed the folder, tried again from scratch and same error

**Comment by unseenmagik** [comment]
![image](https://user-images.githubusercontent.com/30931287/41918586-92a417fe-7954-11e8-8bda-acb8739a6d55.png)

**Comment by coltoutram** [comment]
"pip install ." with the dot

**Comment by unseenmagik** [comment]
That done it, missed the .

![image](https://user-images.githubusercontent.com/30931287/41918783-efa4cb4c-7954-11e8-890f-173174cba1ea.png)

I will reinstall the cog now, reboot the bot and test
thanks

**Comment by coltoutram** [comment]
Np, let me know if theres are any other issues 😄

**Comment by unseenmagik** [comment]
Hay, 

So it installed in this location:
![image](https://user-images.githubusercontent.com/30931287/41958281-7b1b51c8-79e1-11e8-8469-c3d36fd83b80.png)

When i try to load the cog, this is the error from the traceback:
![image](https://user-images.githubusercontent.com/30931287/41958297-8b0da702-79e1-11e8-89f8-1ef2281c4100.png)

I am assuming that the location is not correct or something. 

The cog cannot see the installed files. 

I am running this in a venv if that helps too. I am activated in the evenv when running the commands.

**Comment by unseenmagik** [comment]
Hopefully this will help

```NOTICE: LOADED SPEEDTEST
[27/06/2018 07:18] ERROR events on_command_error 210: Exception in command 'speedtest'
Traceback (most recent call last):
  File "/home/unseenmagik/cloud9mm/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/unseenmagik/.local/share/Red-DiscordBot/MagikBotV3/cogs/CogManager/cogs/speedtest/speedtest.py", line
 45, in speedtest
    speedtest_result = await self.bot.loop.run_in_executor(None, self.speed_test)
  File "/home/unseenmagik/.pyenv/versions/3.6.5/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/unseenmagik/.local/share/Red-DiscordBot/MagikBotV3/cogs/CogManager/cogs/speedtest/speedtest.py", line
 32, in speed_test
    return str(subprocess.check_output(['speedtest-cli'], stderr=subprocess.STDOUT))
  File "/home/unseenmagik/.pyenv/versions/3.6.5/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/unseenmagik/.pyenv/versions/3.6.5/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['speedtest-cli']' returned non-zero exit status 1.```

**Comment by unseenmagik** [comment]
Ok, i resolved this issue but now im facing an issue with the commands

Using the command `[p]bancheck search <user ID>`

This is the error:

```Exception in command 'bancheck search'
Traceback (most recent call last):
  File "/home/unseenmagik/cloud9mm/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/unseenmagik/.local/share/Red-DiscordBot/cogs/CogManager/cogs/bancheck/bancheck.py", line 75, in _banlook
    output = await dBans.lookup(user_id=checkID)
  File "/home/unseenmagik/cloud9mm/lib/python3.6/site-packages/dbans/dbans.py", line 13, in lookup
    raise RuntimeError("User ID not provided")
RuntimeError: User ID not provided

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/unseenmagik/cloud9mm/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/home/unseenmagik/cloud9mm/lib/python3.6/site-packages/discord/ext/commands/core.py", line 927, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  File "/home/unseenmagik/cloud9mm/lib/python3.6/site-packages/discord/ext/commands/core.py", line 514, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/unseenmagik/cloud9mm/lib/python3.6/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: RuntimeError: User ID not provided```
