### ISSUE TITLE
speedtest error

### ISSUE THREAD

**Issue by unseenmagik** [coltoutram/Colts-Cogs#3]
The cog loads ok but uppon running [p]speedtest, the error log is:

`[26/06/2018 10:08] ERROR events on_command_error 210: Exception in command 'speedtest'
Traceback (most recent call last):
  File "/home/unseenmagik/cloud9mm/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrap
ped
    ret = yield from coro(*args, **kwargs)
  File "/home/unseenmagik/.local/share/Red-DiscordBot/MagikBotV3/cogs/CogManager/cogs/speedtest/speedtest.py",
 line 45, in speedtest
    speedtest_result = await self.bot.loop.run_in_executor(None, self.speed_test)
  File "/home/unseenmagik/.pyenv/versions/3.6.5/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/unseenmagik/.local/share/Red-DiscordBot/MagikBotV3/cogs/CogManager/cogs/speedtest/speedtest.py",
 line 32, in speed_test
    return str(subprocess.check_output(['speedtest-cli'], stderr=subprocess.STDOUT))
  File "/home/unseenmagik/.pyenv/versions/3.6.5/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/unseenmagik/.pyenv/versions/3.6.5/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/unseenmagik/.pyenv/versions/3.6.5/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/unseenmagik/.pyenv/versions/3.6.5/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'speedtest-cli': 'speedtest-cli'
`

**Comment by coltoutram** [comment]
You need the speedtest-cli module, just use pip install speedtest-cli

**Comment by unseenmagik** [comment]
Perfect, working now thank you

**Comment by unseenmagik** [comment]
Hi coltoutram,

I have come across another issue with the speedtest cog. 

When running the cog via the launcher, it works fine. 
When i run the cog through systemd .system file the bot throws an error saying that the speedtest-cli package is not installed. 
I have been asking on the Redv3 Support channel in red server and aikaterna asked me to speak with you. 

![image](https://user-images.githubusercontent.com/30931287/41957529-2aeca4f6-79df-11e8-8d75-8190c88ae35d.png)

In your own time, if your able to supprt that would be great. 

Its the same thing for the `bancheck` cog aswell

regards
Magik
